services:
  fsconn:
    build:
      dockerfile: Dockerfile.fsConn.prod
    container_name: fst-fsconn
    restart: always
    # Remove external port exposure, only accessible via internal network
    ports:
      - "51000:51000"   # FS Connection port
    expose:
      - "3000"    # WebSocket Port
    networks:
      - internal_network

  svelte:
    build:
      dockerfile: Dockerfile.svelte.prod
    container_name: fst-frontend
    restart: always
    # Remove external port exposure, only accessible via internal network
    expose:
      - "80"      # Website Port
    networks:
      - internal_network

  nginx:
    image: nginx:1-alpine
    container_name: fst-nginx
    restart: no
    ports:
      - "5000:80"    # Expose NGINX on HTTP port
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/nginx.conf
    depends_on:
      - fsconn
      - svelte
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
