FROM node:20 AS base

FROM base AS builder

WORKDIR /app

COPY ./svelte/package*.json .
#RUN npm ci

COPY ./svelte .
#RUN npm run build
#RUN npm prune --production
#
#FROM base AS runner 
#
#WORKDIR /app/
#
#COPY --from=builder /app/build build/
#COPY --from=builder /app/node_modules node_modules/
#COPY ./svelte/package.json .
#
#EXPOSE 3030
#
#ENV PORT=3030
#ENV BODY_SIZE_LIMIT=Infinity
#
#CMD node build