services:
  fsconn:
    build:
      dockerfile: Dockerfile.fsConn.prod
    container_name: fsconn-server
    restart: always
    ports:
      - "3000:3000"
    networks:
      - internal_network

  svelte:
    build:
      dockerfile: Dockerfile.svelte.prod
    restart: always
    container_name: svelte-frontend
    ports:
      - "80:80"
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
