services:
  fsconn:
    build:
      dockerfile: Dockerfile.fsConn.prod
    container_name: fst-fsconn
    restart: always
    ports:
      - "51000:51000" #port for FS Connection
      - "3000:3000" #Websocket Port
    networks:
      - internal_network

  svelte:
    build:
      dockerfile: Dockerfile.svelte.prod
    restart: always
    container_name: fst-frontend
    ports:
      - "3001:80" #Website Port
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
