// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeFlightSim(arg1) {
  return window['go']['main']['App']['ChangeFlightSim'](arg1);
}

export function GetAircraftName() {
  return window['go']['main']['App']['GetAircraftName']();
}

export function GetConnectionCount() {
  return window['go']['main']['App']['GetConnectionCount']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function ReconnectFlightSim() {
  return window['go']['main']['App']['ReconnectFlightSim']();
}

export function SetCom1ActData(arg1) {
  return window['go']['main']['App']['SetCom1ActData'](arg1);
}

export function SetCom1StbData(arg1) {
  return window['go']['main']['App']['SetCom1StbData'](arg1);
}

export function SetCom1Stby(arg1) {
  return window['go']['main']['App']['SetCom1Stby'](arg1);
}

export function SetCom2ActData(arg1) {
  return window['go']['main']['App']['SetCom2ActData'](arg1);
}

export function SetCom2StbData(arg1) {
  return window['go']['main']['App']['SetCom2StbData'](arg1);
}

export function SetCom2Stby(arg1) {
  return window['go']['main']['App']['SetCom2Stby'](arg1);
}

export function SetFsData(arg1) {
  return window['go']['main']['App']['SetFsData'](arg1);
}

export function SetPosition(arg1, arg2) {
  return window['go']['main']['App']['SetPosition'](arg1, arg2);
}

export function SwitchCom1() {
  return window['go']['main']['App']['SwitchCom1']();
}

export function SwitchCom2() {
  return window['go']['main']['App']['SwitchCom2']();
}
