// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConnectionCount() {
  return window['go']['main']['App']['GetConnectionCount']();
}

export function UpdateAircraftNameAndNotify() {
  return window['go']['main']['App']['UpdateAircraftNameAndNotify']();
}
