// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConnectionCount():Promise<number>;

export function SetCom1Stby(arg1:string):Promise<void>;

export function SetCom2Stby(arg1:string):Promise<void>;

export function SwitchCom1():Promise<void>;

export function SwitchCom2():Promise<void>;

export function UpdateAircraftNameAndNotify():Promise<void>;
