// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeFlightSim(arg1) {
  return window['go']['main']['App']['ChangeFlightSim'](arg1);
}

export function ReconnectFlightSim() {
  return window['go']['main']['App']['ReconnectFlightSim']();
}

export function SetAircraftName(arg1) {
  return window['go']['main']['App']['SetAircraftName'](arg1);
}

export function SetCom1Stby(arg1) {
  return window['go']['main']['App']['SetCom1Stby'](arg1);
}

export function SetCom2Stby(arg1) {
  return window['go']['main']['App']['SetCom2Stby'](arg1);
}

export function SetConnectionCount(arg1) {
  return window['go']['main']['App']['SetConnectionCount'](arg1);
}

export function SetConnectionStatus(arg1) {
  return window['go']['main']['App']['SetConnectionStatus'](arg1);
}

export function SetFsData(arg1) {
  return window['go']['main']['App']['SetFsData'](arg1);
}

export function SwitchCom1() {
  return window['go']['main']['App']['SwitchCom1']();
}

export function SwitchCom2() {
  return window['go']['main']['App']['SwitchCom2']();
}
